import Head from 'next/head'
import Link from "next/link"
import { sanityClient, urlFor } from "../client"
import {
  Title,
  PostTitle,
  IndexPostGrid,
  Wrapper
} from '../components/styles/Grid.styled'


export default function Home({posts}) { 
  return (
    <>
      <Head>
        <title>Writing to Better Health | Cooking Notes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Title>Biochemistry</Title>
          <Wrapper>
          <IndexPostGrid> 
            {posts &&
            posts.map((post, index) => (   
              <Link href={`post/${post.slug.current}`}>
                <span key={index}>
                  <div className="square"> 
                  <img 
                  src={urlFor(post.mainImage)}
                  alt="main pic"
                  className="image"
                  />
                  <PostTitle>{post.title}</PostTitle>
                  </div>
                </span>
              </Link>
            ))}
              </IndexPostGrid>
          </Wrapper>
    </>
  )
}

export const getServerSideProps = async () => {
  const query = '*[ _type == "portionCtrl"] | order(_createdAt desc)'
  const posts = await sanityClient.fetch(query)

  if (!posts.length) {
    return {
      props: {
        posts: [],
      },
    }
  } else {
    return {
      props: {
        posts,
      },
    }
  }
}
 