import Head from 'next/head'
import Link from "next/link"
import { sanityClient, urlFor } from "../client"
import Navbar from '../components/Navbar'

import {
  Wrapper,
  Grid,
  NavbarWrapper,
  ImageWrapper,
  PostsContainer,
  PostTitle
} from '../components/styles/CategoryPages.styled.js'
import styled from 'styled-components'


//STYLES
 

export const BlogTitle = styled.h2`
display: flex;
justify-content: center;
background: teal;
font-size: 30px;
margin-top: 50px;
margin-bottom: 5px;
padding: 10px;
border: solid 2px black;
`
 
 
//END STYLES



const Biochemistry = ({ posts }) => {
  return (
    <>
      <Head>
        <title>Writing to Better Health | Cooking Notes</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <BlogTitle>Biochemistry</BlogTitle>
                   <Wrapper> 
                    <Grid>

                    <NavbarWrapper>
                    <Navbar />
                    </NavbarWrapper>  
                    
                   <PostsContainer>
                   {posts &&
                    posts.map((post, index) => (
                      <span key={index}>
                      <PostTitle>{post.biochemTitle}</PostTitle>
                      <ImageWrapper>
                      <img
                       src={urlFor(post.biochemImage)}
                       className="img"
                       width={350}
                       height={300}
                       />
                      </ImageWrapper>
                      </span>
                    ))
                    }
                    </PostsContainer>
                    </Grid>
                   </Wrapper>
    </>
  )
}
 
export const getServerSideProps = async () => {
  const query = '*[_type == "biochemistry"]'
  const posts = await sanityClient.fetch(query)

  if(!posts.length) {
    return {
      props: {
        posts: [],
      },
    }
  } else {
    return {
      props: {
        posts,
      },
    }
  }
}

export default Biochemistry
