import Head from 'next/head'
import Link from "next/link"
import { sanityClient, urlFor } from "../client"
import styled from 'styled-components'
import Navbar from '../components/Navbar'



//STYLES
 const Wrapper = styled.div`
  // background: teal;
  width: 100%;  
  display: flex;
  justify-content: center;
`

const Grid = styled.div`
display: grid;
grid-template-columns: 200px 1fr;
grid-template-areas: 
'a b';

@media only screen and (max-width: 531px) {
  display: grid;
  grid-template-columns: 1fr;
  grid-template-rows: 1fr 1fr;
  grid-template-areas: 
  'a' 
  'b';
}
`

const NavbarWrapper = styled.div`
grid-area: a;
// background: coral;
display: flex;
justify-content: center;
padding-top: 100px; 
`


export const BlogTitle = styled.h2`
display: flex;
justify-content: center;
background: coral;
font-size: 30px;
margin-top: 50px;
margin-bottom: 5px;
padding: 10px;
border: solid 2px black;
`

export const ImageWrapper = styled.div`
display: flex;
justify-content: center;
 .img {
  border: solid 2px black;
 }
`

export const PostsContainer = styled.div`
// background: teal;
 display: grid;
 grid-template-columns: repeat(3, 400px);
 grid-area: b;
`

export const PostTitle = styled.h3`
text-align: center;
padding: 10px;
color: teal;
`
//END STYLES



const Blog = ({ posts }) => {
  return (
    <>
      <Head>
        <title>Writing to Better Health | Cooking Notes</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <BlogTitle>Blog</BlogTitle>
                   <Wrapper> 
                    <Grid>

                    <NavbarWrapper>
                    <Navbar />
                    </NavbarWrapper>
                    
                   <PostsContainer>
                   {posts &&
                    posts.map((post, index) => (
                      <span key={index}>
                      <PostTitle>{post.postTitle}</PostTitle>
                      <ImageWrapper>
                      <img
                       src={urlFor(post.mainImage)}
                       className="img"
                       width={350}
                       height={320}
                       />
                      </ImageWrapper>
                      </span>
                    ))
                    }
                    </PostsContainer>
                    </Grid>
                   </Wrapper>
    </>
  )
}
 
export const getServerSideProps = async () => {
  const query = '*[_type == "blogPosts"]'
  const posts = await sanityClient.fetch(query)

  if(!posts.length) {
    return {
      props: {
        posts: [],
      },
    }
  } else {
    return {
      props: {
        posts,
      },
    }
  }
}

export default Blog
