import Head from 'next/head'
import Link from "next/link"
import Contact from '../components/Contact'
import TopicsBannerCTA from '../components/TopicsBanner'
import About from '../components/About'
import styled from 'styled-components'



//STYLES 
export const MostRecentWrapper = styled.div`
display: flex;
justify-content: center;
flex-direction: column;
padding: 45px 150px;
margin-top: 100px;
margin-bottom: 50px;
text-align: center;
// background: aquamarine;

@media only screen and (max-width: 1024px) {
  padding: 0 40px;
}
`


export const BlogTitle = styled.h2`
display: flex;
justify-content: center;
background: coral;
font-size: 30px;
padding: 10px;
border: solid 2px black;
`

export const ImageWrapper = styled.div`
display: flex;
justify-content: center;
 .img {
  border: solid 2px black;
  width: 320px;
height: 220px;
 }
`

export const PostsContainer = styled.div`
 display: grid;
 grid-template-columns: repeat(4, 1fr);
padding: 50px;
`

export const PostTitle = styled.h3`
text-align: center;
`


export const RecentPostTitle = styled.h2`
text-decoration: underline;
`

export const RecentBlogPostTitle = styled.h4`
// color: teal;
margin: 10px;
`
//END STYLES



const Home = ({ posts }) => {
  return (
    <>
      <Head>
        <title>Writing to Better Health | Cooking Notes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
           <TopicsBannerCTA />  
                   <MostRecentWrapper>
                   <RecentPostTitle>Most Recent Post</RecentPostTitle>
                   <RecentBlogPostTitle>First post</RecentBlogPostTitle>
                   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam inventore ratione, est similique molestiae eius esse sit ea assumenda architecto aperiam nihil, doloribus quae debitis rerum quidem! Eaque, itaque quibusdam. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam inventore ratione, est similique molestiae eius esse sit ea assumenda architecto aperiam nihil, doloribus quae debitis rerum quidem! Eaque, itaque qui Read More...</p>
                   </MostRecentWrapper>
         <About />
         <Contact />
   </>
  )
}
  

export default Home
