import Head from 'next/head'
import Link from "next/link"
import Image from "next/image"
import { sanityClient, urlFor } from "../client"
import Contact from '../components/Contact'
import TopicsBannerCTA from '../components/TopicsBanner'
import About from '../components/About'
import {
  ContentWrapper,  
  BlogWrapper,
  CookingNotesWrapper,
  BiochemistryWrapper
} from '../components/styles/Index.styled'
  



const Home = ({ posts }) => {
  return (
    <>
      <Head>
        <title>Writing to Better Health | Cooking Notes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
           <TopicsBannerCTA />


                  <ContentWrapper>
                    Blog
                   <BlogWrapper> 
                   {posts &&
                    posts.map((post) => (
                      <div>
                      <h1>{post.postTitle}</h1>
                      <div>{post.postDescription}</div>
                      </div>
                    ))
                    }
                   </BlogWrapper>

                    <CookingNotesWrapper> 
                      Cooking Notes
                    {posts &&
                      posts.map((post) => (
                        <div>
                        <h1>{post.cookTitle}</h1>
                        <div>{post.cookDescription}</div>
                        </div>
                      ))
                      }
                    </CookingNotesWrapper>

                    <BiochemistryWrapper> 
                      Biochemistry
                   {posts &&
                    posts.map((post) => (
                      <div>
                      <h1>{post.biochemTitle}</h1>
                      <div>{post.biochemDescription}</div>
                      </div>
                    ))
                    }
                   </BiochemistryWrapper>
                   </ContentWrapper>
         <About />
         <Contact />
       
    </>
  )
}
 
export const getServerSideProps = async () => {
  const query = '*[_type in ["blogPosts", "cookingNotes", "biochemistry"]]'
  const posts = await sanityClient.fetch(query)

  if(!posts.length) {
    return {
      props: {
        posts: [],
      },
    }
  } else {
    return {
      props: {
        posts,
      },
    }
  }
}

export default Home
