import Head from 'next/head'
import Link from "next/link"


import { sanityClient, urlFor } from "../client"
import {
  PageTitle,
  Wrapper,
  PostLinks,
  PostTitle,
  ImgWrapper,
  SplicedContent,
  CTA
} from '../components/styles/Index.styled'




export default function Home({posts}) {
  return (
    <>
      <Head>
        <title>Writing to Better Health</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
      <PageTitle>Recent Posts</PageTitle>
   
      <Wrapper>
      <PostLinks> 
        {posts &&
        posts.map((post, index) => (   
          <Link href={`post/${post.slug.current}`}>
            <span key={index}>
            <hr />
            <PostTitle>{post.title}</PostTitle>
              <ImgWrapper>
              <img
               src={urlFor(post.mainImage)}
               alt="main pic"
               className="image"
               />
               </ImgWrapper>
               <SplicedContent>
     Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos velit magni a voluptas debitis neque tempore laudantium, quaerat ratione atque dolor ut fugit. Quo vero impedit, nisi tempora maxime itaque...
     </SplicedContent>
   
              <CTA>
                Read more
              </CTA>
            </span>
           
           </Link>
        ))}
          </PostLinks>
         
      </Wrapper>
      
    </>
  )
}


export const getServerSideProps = async () => {
  const query = '*[_type in ["portionCtrl", "food", "nutritionalBiochemistry"]] | order(_createdAt desc)'
  const posts = await sanityClient.fetch(query)

  if (!posts.length) {
    return {
      props: {
        posts: [],
      },
    }
  } else {
    return {
      props: {
        posts,
      },
    }
  }
}
 