import Head from 'next/head'
import Link from "next/link"

import { sanityClient, urlFor } from "../client"
import {
  PageTitle,
  Wrapper,
  PostLinks,
  PostTitle,
  SpliceContent,
  ImgWrapper
} from '../components/styles/ComicPage.styled'




export default function Home({posts}) {
  return (
    <>
      <Head>
        <title>Writing to Better Health | Portion Ctrl Comics</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageTitle>Portion Ctrl Comics</PageTitle>

   
      <Wrapper>
        
      <PostLinks> 
        {posts &&
        posts.map((post, index) => (   
          <Link href={`post/${post.slug.current}`}>
            <span key={index}>


              <ImgWrapper>
              <img 
               src={urlFor(post.mainImage)}
               alt="main pic"
               className="image"
               width="600"
               height="200"
               />
               <SpliceContent>
            <PostTitle>{post.title}</PostTitle> 
             <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero eaque ad corrupti voluptates. Ad, distinctio quod nam reprehenderit perspiciatis illo aut iusto minima provident architecto corporis numquam fuga! Error, temporibus.
                Read More...
                </p> 
               </SpliceContent>
              </ImgWrapper>
              <hr />
            </span>
           </Link>
        ))}
          </PostLinks>
      </Wrapper>
    </>
  )
}


export const getServerSideProps = async () => {
  const query = '*[ _type == "portionCtrl"] | order(_createdAt desc)'
  const posts = await sanityClient.fetch(query)

  if (!posts.length) {
    return {
      props: {
        posts: [],
      },
    }
  } else {
    return {
      props: {
        posts,
      },
    }
  }
}
 